services:
  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    depends_on:
      - db
      - redis

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - judge0-db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0secret
      POSTGRES_DB: judge0

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - judge0-redis:/data

volumes:
  judge0-db:
  judge0-redis:
